export interface Card {
    name: string,
    symbol: string,
    event: string
}

export class CardsUtil {

    public static cards: Array<Card> = [
        { name: "A", symbol: "♥", event: "heartsDropped" },
        { name: "A", symbol: "♦", event: "diamondDropped" },
        { name: "A", symbol: "♠", event: "spadesDropped" },
        { name: "A", symbol: "♣", event: "clubDropped" },
        { name: "2", symbol: "♥", event: "heartsDropped" },
        { name: "2", symbol: "♦", event: "diamondDropped" },
        { name: "2", symbol: "♠", event: "spadesDropped" },
        { name: "2", symbol: "♣", event: "clubDropped" },
        { name: "3", symbol: "♥", event: "heartsDropped" },
        { name: "3", symbol: "♦", event: "diamondDropped" },
        { name: "3", symbol: "♠", event: "spadesDropped" },
        { name: "3", symbol: "♣", event: "clubDropped" },
        { name: "4", symbol: "♥", event: "heartsDropped" },
        { name: "4", symbol: "♦", event: "diamondDropped" },
        { name: "4", symbol: "♠", event: "spadesDropped" },
        { name: "4", symbol: "♣", event: "clubDropped" },
        { name: "5", symbol: "♥", event: "heartsDropped" },
        { name: "5", symbol: "♦", event: "diamondDropped" },
        { name: "5", symbol: "♠", event: "spadesDropped" },
        { name: "5", symbol: "♣", event: "clubDropped" },
        { name: "6", symbol: "♥", event: "heartsDropped" },
        { name: "6", symbol: "♦", event: "diamondDropped" },
        { name: "6", symbol: "♠", event: "spadesDropped" },
        { name: "6", symbol: "♣", event: "clubDropped" },
        { name: "7", symbol: "♥", event: "heartsDropped" },
        { name: "7", symbol: "♦", event: "diamondDropped" },
        { name: "7", symbol: "♠", event: "spadesDropped" },
        { name: "7", symbol: "♣", event: "clubDropped" },
        { name: "8", symbol: "♥", event: "heartsDropped" },
        { name: "8", symbol: "♦", event: "diamondDropped" },
        { name: "8", symbol: "♠", event: "spadesDropped" },
        { name: "8", symbol: "♣", event: "clubDropped" },
        { name: "9", symbol: "♥", event: "heartsDropped" },
        { name: "9", symbol: "♦", event: "diamondDropped" },
        { name: "9", symbol: "♠", event: "spadesDropped" },
        { name: "9", symbol: "♣", event: "clubDropped" },
        { name: "10", symbol: "♥", event: "heartsDropped" },
        { name: "10", symbol: "♦", event: "diamondDropped" },
        { name: "10", symbol: "♠", event: "spadesDropped" },
        { name: "10", symbol: "♣", event: "clubDropped" },
        { name: "J", symbol: "♥", event: "heartsDropped" },
        { name: "J", symbol: "♦", event: "diamondDropped" },
        { name: "J", symbol: "♠", event: "spadesDropped" },
        { name: "J", symbol: "♣", event: "clubDropped" },
        { name: "Q", symbol: "♥", event: "heartsDropped" },
        { name: "Q", symbol: "♦", event: "diamondDropped" },
        { name: "Q", symbol: "♠", event: "spadesDropped" },
        { name: "Q", symbol: "♣", event: "clubDropped" },
        { name: "K", symbol: "♥", event: "heartsDropped" },
        { name: "K", symbol: "♦", event: "diamondDropped" },
        { name: "K", symbol: "♠", event: "spadesDropped" },
        { name: "K", symbol: "♣", event: "clubDropped" }
    ]

}